CREATE TABLE IF NOT EXISTS `perfil` (
  `SQL_ROWID` int(11) NOT NULL AUTO_INCREMENT,
  `PER_NOM` varchar(60) DEFAULT NULL,
  `PER_EMA` varchar(100) DEFAULT NULL,
  `PER_SEN` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`SQL_ROWID`),
  UNIQUE KEY `sql_rowid_UNIQUE` (`SQL_ROWID`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=latin1;

INSERT INTO `perfil` (`SQL_ROWID`, `PER_NOM`, `PER_EMA`, `PER_SEN`) VALUES
	('Teste', 'teste@gmail.com', '$2a$08$MTA4Mjc1Njc4MDU3N2UyOOpaMMz65IX0PWxMvEK8EfHiXwuPs6Kb.');
